/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.model.Aluno;
import org.example.model.MediaCalculator;
import org.example.model.MediaQualifier;

import java.util.Scanner;

public class App {


    public static void main(String[] args) {
        new App().run();
    }

    public void run() {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Informe o nome do aluno:");
        Aluno aluno;
        aluno = new Aluno("aawda");
        aluno.addNota(3f,5f,6f);
        try {
            String nome = scanner.nextLine();
            aluno = new Aluno(nome);
            System.out.print("Nota 1:");
            aluno.addNota(scanner.nextFloat());
            System.out.print("Nota 2:");
            aluno.addNota(scanner.nextFloat());
            System.out.print("Nota 3:");
            aluno.addNota(scanner.nextFloat());
            Float media = new MediaCalculator().calcular(aluno.getNotas());
            String status = new MediaQualifier().qualificar(media);
            System.out.println("Aluno: " + aluno.getNome());
            System.out.println("Notas: " + aluno.getNotas());
            System.out.println("Média: " + media);
            System.out.println("Situação: " + status);
        } catch (Exception ex) {
            System.out.println("ERRO! Valor informado inválido!");
            System.exit(1);
        }




    }
}
